# Grafana Datasource Provisioning Configuration
# Reference: https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
# 
# This file is automatically read by Grafana to provision datasources
# Place this file in: /etc/grafana/provisioning/datasources/

apiVersion: 1

# List of data sources to delete from the database
deleteDatasources: []

# Mark provisioned data sources for deletion if they are no longer in a provisioning file
prune: false

# List of data sources to insert/update
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    url: http://medisecure-prometheus:9090
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      timeInterval: '15s'
    version: 1
